### ISSUE TITLE
Why is JWT issuer metadata part of this spec?

### ISSUE THREAD

**Issue by andresuribe87** [oauth-wg/oauth-sd-jwt-vc#112]
Mechanisms to go from `iss` -> cryptographic public key that can be used for signature verification seem to be out of scope for this document. Why is it included?

**Comment by alenhorvat** [comment]
Is the purpose of the issuer metadata to provide an alternative to x509 certificates (that can today be shared via the x* header claims)?

**Comment by tlodderstedt** [comment]
> Mechanisms to go from iss -> cryptographic public key that can be used for signature verification seem to be out of scope for this document. Why is it included?

We could have put that in a separate spec, but that would have been a very small one. We felt JWT issuer metadata is tightly enough related to VCs that having the meta and configuration data distribution mechanism in the same spec as the VCs makes sense.  

> Is the purpose of the issuer metadata to provide an alternative to x509 certificates (that can today be shared via the x* header claims)?

We want to provide implementers a simple way to resolve keys similar to how OpenID Connect does it. And yes, that is an alternative to x.509, but also other mechanisms, like DIDs.

**Comment by alenhorvat** [comment]
_We could have put that in a separate spec, but that would have been a very small one. We felt JWT issuer metadata is tightly enough related to VCs that having the meta and configuration data distribution mechanism in the same spec as the VCs makes sense._

Resolving keys without an ability to resolve information about key attestation/certificates, etc., is not enough. The proposed model works under assumption that there is a relationship between all the participants since only key is resolved. For an open system, the metadata should return more information, like key attestations, trust chains, accreditations, and other.

If the specs are aiming at closed systems where all the rules are clear, the proposal is fine. Else, a separate specification (that would be much more elaborate) would be required.

The model assumes .well-known endpoint which makes it compatible only with did:web. Why not using DID web then? with additional query parameter DID method should be able to return a specific key in a defined format, e.g., jwk (I cannot find the specs but I think DID resolver supports this)

**Comment by tlodderstedt** [comment]
> The proposed model works under assumption that there is a relationship between all the participants since only key is resolved. 

The concept works very well for open systems: The key distribution with `jwt-issuer` allows the verifier to authenticate the issuer URL. The assumption of the model is that additional data can be provided using suitable mechanisms on top of the (authenticated) issuer URL as identifier. For example, a trusted registry could list the issuers trusted for a certain purpose.

> The model assumes .well-known endpoint which makes it compatible only with did:web. 

.well-known is a mechanism widely used by a number of standards. Thus `.well-known/jwt-issuer` is compatible with a large number of other well-known locations, including `openid-credential-issuer`, `oauth-authorization-server` and `openid-federation` (even `openid-configuration`). So implementations can share role specific meta and configuration data based on a single service identifier in a modular fashion. Additionally, `openid-federation` can be used to anchor the issuer within a trust graph, which allows to establish trust and share policies in a quite flexible manner (which adds to your first point).

A credential issuer could, for example, host metadata in all those locations and clients can access whatever is needed for their respective use case. 
```
<issuer URL>/.well-known
                          jwt-issuer (verifier perspective, mainly keys)
                          openid-credential-issuer (wallet perspective, available credential types, endpoints)
                          oauth-authorization-server (OAuth endpoints and capabilities)
                          openid-federation (trust anchors, ...)
```
                   
did:web, in contrast, tries to bundle all kinds of metadata in a single location, i.e. it does not embrace the modular concept of .well-known.

**Comment by danielfett** [comment]
@tlodderstedt This question came up a couple of times already. Can you please provide a PR with some considerations along the lines of what you said above for inclusion in the spec?

**Comment by awoie** [comment]
related to #168

**Comment by awoie** [comment]
We introduced a PR #175 that explains the role of the JWT Issuer Metadata that fills the gap of key discovery if the issuer is a HTTPS URI. Note, DIDs are also mentioned as another option explicitly.

**Comment by awoie** [comment]
Closing this issue since PR #175 got merged.
