### ISSUE TITLE
Provide W3C VCDM transformation algorithm

### ISSUE THREAD

**Issue by andresuribe87** [oauth-wg/oauth-sd-jwt-vc#114]
I found it hard to understand the relationship between VC's and the spec. Specifically, it's not clear to me how to go from VC (as in `application/vc+ld+json`) to `SD-JWT VC`, nor the other way.

**Comment by awoie** [comment]
The specification does not use the W3C VCDM. A note was added to the spec. We might add a transformation algorithm from SD-JWT VC to W3C VCDM in the future if needed. This also depends on the implementation of the Miami resolution.

I'll rename the issue to make it clear that this is about a transformation algorithm and we will revisit in the future.

**Comment by Sakurann** [comment]
Transforming syntax between w3c vcdm payload and sd-jwt vc payload is probably not too complicated. it is more about mapping between the claims (i.e. issuer -> iss; issuanceData -> iat, etc.) and handling when representation of a claim is different (i.e. when issuer is an object in vcdm but is a string in sd-jwt vc, etc.)

the bigger problem is semantics. sd-jwt vc -> vcdm might work by using default context thanks to the @vocab value there that will tell json-ld parser to treat all undefined terms as #issuerDefined. not sure how much vcdm -> sd-jwt vc is possible because sd-jwt vc does not have `@context` value by definition. so in any case, semantics ie meaning of varying claims will probably need to be agreed out of band.

**Comment by babisRoutis** [comment]
> Thoughts?

I really like the fact that SD JWT VC is not related to the W3C VC DM, or any other format.
This independence allows this specification to present SD JWT VC as a new clean format.

I really see no point in adding mapping rules or describing approaches to map between formats.

**Comment by awoie** [comment]
I think, we had a lot of discussions on this and nobody argued for having a transformation algorithm being defined in this specification. I suggest to close this issue after 1 week unless anybody feels very strongly.
