### ISSUE TITLE
Is the following a valid SD-JWT-VC or how can it be mapped to the SD-JWT-VC?

### ISSUE THREAD

**Issue by alenhorvat** [oauth-wg/oauth-sd-jwt-vc#121]
<img width="591" alt="image" src="https://github.com/vcstuff/draft-terbu-sd-jwt-vc/assets/10848802/48c0ead3-3657-4cf5-8380-6bcb6063ce08">

All the claims need to be present, along with the @context.

Would this be a valid SD-JWT-VC?

**Comment by tlodderstedt** [comment]
From first read, mostly, however, the processing result might not what you would expect. 

The "type" violates the definition in SD-JWT VC. 

I miss the JOSE header, which is important as it marks SD-JWT VCs as such (with the `typ` `vc+sd-jwt`).  

Interpretation of "@context", "id", "credentialSubject", "credentialStatus", "credentialSchema", "termsOfUse" is up to your application. 

There will be a status management mechanism in SD-JWT VC similar to credentialStatus but using the JWT `status` to represent the status list (https://github.com/vcstuff/draft-looker-jwt-cwt-status-list). 

I guess "credentialSubject" is intended to be used for holder binding. SD-JWT VC uses the JWT `cnf` claim for that purpose. 

I think we could come up with a JWTish equivalent to "termsOfUse".

"type" is defined single value for SD-JWT VC - I'm not sure which of the type information in your example I would put into the "type" claim of a SD-JWT VC. "VerifiableCredential" is already covered by the "typ" JOSE header "vc+sd-jwt". "VerifiableAttestation" does not sound that much different. Not sure how to interpret the "credentialSchema". 

I see two directions: 

1. You may modify the content to use JWT claims.
2. You can use a different kind of SD-JWT envelop to carry the current JSON-LD (inspired) content (which would use a different `typ` header).

**Comment by alenhorvat** [comment]
- We need the "type" to support an array of strings.
- We define our own status and the status list should support an object
- credentialSubject contains domain-specific claims about the subject (name, ...)
- termsOfUse is currently misused; we need to express: rules what the credential can be used for (termsOfUse name is appropriate), and to express the accreditation information/trust information/...

typ header is not working for us, since we need an ability to arbitrarily extend the schema. Type as array is the best approach so far

I need to think about the header type names.

**Comment by alenhorvat** [comment]
- credentialSchema references JSON schema that used to validate the VC format and plays a role when it comes to accreditations; in open systems, it is an important information
- type: Verifiable Credential defines the data model as per w3c vc; Verifiable Attestation data model extends the VC data model; other credentials that we're using: V. Authorisation to Onboard, V. Authorisation for Trust Chain, V. Accreditation for accrediting, V. Accreditation for attesting all extend the V. Attestation.
- Domains that define the data models also extend the V. Attestation data model
Hence the type and credentialSchema claims play an important role in an open ecosystem as it allows coherent data modelling across different domains.

**Comment by alenhorvat** [comment]
The relevant header typ values would be
- vc+json+jwt - VCDM + JWT claims processed as JSON
- vc+json-ld+jwt - VCDM + JWT claims processed as JSON-LD
- vc+json+sd+jwt - same as above, except that it is SD
- vc+json-ld+sd+jwt - same as above, except that is SD

If SD-JWT has 0 hidden claims, it boils down to JWT-VC? If yes, then one needs only last 2

It is inappropriate to put the type values I'm mentioning above, in the typ header value since it is not a new media type, but an extended data model

**Comment by alenhorvat** [comment]
Based on experience and feedback from a wide range of stakeholders, a full data model should contain the following claims:
Important property is that use cases have the ability to extend the different claims when required.

```jsonc
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1"
  ], // Type: array of URIs. Use: CONDITIONAL: If credential is JSON-LD, the claim MUST be present, else it MUST NOT be present

  "iss": "did:ebsi:alice", // Type: String (URI) or object. Use: REQUIRED
  "aud": "did:ebsi:bob", // Type: String (URI) or object. Use: OPTIONAL

  "id": "urn:uuid:003a1dd8-a5d2-42ef-8182-e921c0a9f2cd", // Unique ID of the credential. Use: OPTIONAL

  // Credential validity information. 
  "validity": {
    "iat": "2021-11-01T00:00:00Z", // Date and time of issuance - required
    "exp": "2024-06-22T14:11:44Z", // Date at and after which the VC MUST be considered invalid - optional - e.g., credential cannot be used for online authentication (e.g., the bound key/certificate expired), but can be used for offline identification where person is compared against the photo if notAfter > exp.
    "nbf": "2024-06-22T14:11:44Z", // date at an after which the VC is valid (e.g., signature expires) - optional
    "notAfter": "2024-06-22T14:11:44Z" // Date and time after which the business content becomes invalid - optional 
  },

  // REQUIRED. String or object
  "subject": {
    // If object, type MUST be present and define the business type of the credential. Can be string or array
    "type": [
      "VerifiableCredential",
      "VerifiableAttestation", "VerifiableID"
    ],
    "id": "did:ebsi:00001235" // optional - subject identifier
  },

  // OPTIONAL. Cryptographic binding information. Can be JWK or other object/string
  "cnf": {},

  // OPTIONAL. Credential status. MUST be object. Type determines the processing rules and the additional claims
  "status": { 
    "type": "AnyExtension"
  },

  // OPTIONAL. JSON schema that validates the credential. Type: object. Type determines the validation rules
  "schema": {
    "id": "https://api-test.ebsi.eu/trusted-schemas-registry/v2/schemas/0x23039e6356ea6b703ce672e7cfac0b42765b150f63df78e2bd18ae785787f6a2",
    "type": "FullJsonSchemaValidator2021"
  },

  // OPTIONAL. Defines the rules and limitations when/how the credential can be used/consumed. E.g., medical data can be shared only with certified entities, diploma cannot be used for identification, ...; Type: object or array of objects
  "termsOfUse": {
    "type": "AnyExtension"
  },

  // OPTIONAL. Contains all the necessary information about the trust chain. Can be Federation Trust Chain, Accreditation chain, etc.; Type: object or array of objects
  "trustChain": {
    "type": "AnyExtension"
  },

  // OPTIONAL. Contains information about rendering. Type determines the processing rules.
  "rendering": {
    "type": "AnyExtension"
  }
}
```

**Comment by tlodderstedt** [comment]
Hi @alenhorvat, 

you have added a lot of information to this issue. I suggest we discuss them step by step. 

I would like to start with `type` vs `typ`. 

The JOSE `typ` header is used to determine the structure and processing rules of the payload. The `typ` value `vc+sd-jwt` indicates "this thing is a VC with pure JSON content following the rules defined for JWTs and it can selectively disclosed using SD-JWT + there are some more rules defined in the sd-jwt vc spec". This `typ` value plays the same role the "VerifiableCredential" type values has in the VCDM. So we don't need it in the `type`.

Part of the rules defined for `vc+sd-jwt` is the presence of the `type` claim. 

> This specification defines the JWT claim type. The type claim is used to express the type of the JSON object that is secured by the JWT. The type value MUST be a case-sensitive StringOrURI value.

This is an application type, such as "MyEMailCredential", so it basically tells you what end-user (or subject) claims to expect in this type of a credential. The `type` value is especially important for presentation requests, as it used to determine the kind of credential that is being requested and it also determines what claims can be used to filter matching credentials and those claims can also be selectively disclosed. 

To me, the `type` as defined in sd-jwt vc and `type` as well as `credentialSchema` that you use have a similar purpose. 

I have a couple of questions to that end: 

1. Can you shed some light on why you use both, `type` and `credentialSchema`? The reason why I'm asking is, I assume the schema could be derived from the type value or the type value could even be the schema URL. 
2. Can you please share examples of credentials where you use two or more type values in addition to the "VerifiableCredential". The reason I'm asking is, in my observation VCs typically have the "VerifiableCredential" value plus another application specific type. As "VerifiableCredential" is replaced in sd-jwt vc by the `typ`value, we have come to the conclusion (for now), a String literal is enough. I'm a bit hesitant to make that an array because I think there might be unintended consequences as clashes between rules defined for the different VC types.

**Comment by awoie** [comment]
@alenhorvat The example you provided is not a valid SD-JWT VC because the `type` cannot be an array. Also note, we have an existing issue to rename `type` which would have an impact on your example. In your new example, `iat` is supposed to be at the top-level and not inside the `validity` claim. Does this answer your question?

If you want to have something changed, please create a more specific issue.

**Comment by alenhorvat** [comment]
No. If it cannot be mapped, it's quite an issue. Ignore the "validity" claim.

**Comment by peacekeeper** [comment]
> I guess "credentialSubject" is intended to be used for holder binding.

> credentialSubject contains domain-specific claims about the subject (name, ...)

This example also uses "credentialSubject": https://datatracker.ietf.org/doc/html/draft-ietf-oauth-selective-disclosure-jwt-04#name-example-4a-w3c-verifiable-c

**Comment by peacekeeper** [comment]
Regarding mapping VCDM `type` (array) and JWT `vct` (single value), someone in the EU ARF community proposed that the array values could be concatenated and separated by a `;` semicolon, e.g. `"vct": "VerifiableAttestation;VerifiableID"`, but I think hacks like that will never work in practice...

**Comment by paulbastian** [comment]
I believe there will be situations where both
- an SD-JWT-VC vct already exists
- an corresponding jsonld type already exists

In these cases an automatic general purpose transformation would not work.
So in my opinion it depends on the use case.

**Comment by alenhorvat** [comment]
Since this draft is far less used and implemented as VCDM, is there an option to make this data model open enough to make mapping possible?

**Comment by awoie** [comment]
> Since this draft is far less used and implemented as VCDM, is there an option to make this data model open enough to make mapping possible?

Why do you think a mapping is not possible? IMO, the mapping has to be done on a specific `vct` credential type since prior knowledge of context URIs, and VC metadata is required.

What would be the purpose of such a mapping? Is the goal that on the other end, you would get an unsecured VCDM credential?

**Comment by awoie** [comment]
Perhaps we can add a JSON patch to the Credential Metadata which is type-specific that converts the SD-JWT VC to a VCDM.

**Comment by awoie** [comment]
I suggest we mark this as pending close since we agreed to move towards https://github.com/danielfett/sd-jwt-vc-dm. I suggest closing this issue after 1 week unless somebody disagrees.

**Comment by alenhorvat** [comment]
Hi. @awoie @danielfett, is the latest PR (https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/251) in line with the agreement to move towards sd-jwt-vc dm?
