### ISSUE TITLE
JWT Issuer Metadata: Why is jwks_uri recommended over jwks?

### ISSUE THREAD

**Issue by tlodderstedt** [oauth-wg/oauth-sd-jwt-vc#125]
I would like to understand why the draft recommends use of `jwks_uri` as way to refer to the issuer's key set. I personally would recommend `jwks` as it saves one HTTP request/response. I would only recommend `jwks_uri` for cases where the issuing entity has multiple roles using the same key set and want to keep that in a single place.

**Comment by bc-pi** [comment]
I would recommend having only the jwks_uri. 

It allows the issuer to manage (rotate, set cache duration, etc) it's keys independent of any other metadata and in a location other than under .well-known, which can be be a difficult place in some deployments to have dynamic content. 

Also many JWT/JOSE libraries have existing robust support for resolving keys from a JWKS endpoint and dealing with caching and new kid values etc. But the same functionality isn't present for getting the keys from within a JSON document with other content.

Having both jwks_uri and jwk complicates things for every entity that is verifying signatures on these things because they have to account for both.

**Comment by peppelinux** [comment]
I agree that jwks Is Better since It doesnt require additional http requests

That's why in oidc federation we have enabled jwks also for oidc op

And more, having a static and verifiable attestation of a metadata (signed!) makes the flow possible also in offline use cases, while using jwks_uri won't

**Comment by paulbastian** [comment]
I think having both options is valid. I agree that I don't see enough reason to recommend one over the other

**Comment by awoie** [comment]
Agreed to remove recommendation but keeping both options
