### ISSUE TITLE
Add privacy considerations for JWT issuer metadata - privacy concerns

### ISSUE THREAD

**Issue by alenhorvat** [oauth-wg/oauth-sd-jwt-vc#127]
JWT issuer metadata, as defined in this document, is raising privacy concerns since verifiers will need to contact issuers directly which basically maps to the existing authentication model. Question is, why not just using the existing OIDC/SAML infrastructure instead?

**Comment by awoie** [comment]
> JWT issuer metadata, as defined in this document, is raising privacy concerns since verifiers will need to contact issuers directly which basically maps to the existing authentication model. Question is, why not just using the existing OIDC/SAML infrastructure instead?

I don't think that this is an issue for non-malicious issuers. Normally, there is no correlation between the issuer key and the user (citizen). This is because the issuer probably uses the same key for a large number of users and VCs.

However, if an issuer would create keys per user, then indeed the issuer could track a user but this is something that would be detectable and it probably also have some legal implications for the issuer. In general, we can agree this is something that when becomes public, would harm the reputation of the issuer. Furthermore, hi-assurance VC issuers would probably want to use HSMs for signing which in that case would be impractical for cost-efficiency reasons. HSMs are expensive. I do agree though that there is a risk that malicious issuers could create special keys for special users i.e. targeted attacks, but this would be also detectable.

IMO, we should add something to the privacy considerations section.

**Comment by awoie** [comment]
Added privacy considerations; PR #48 got merged, closing this issue.
