### ISSUE TITLE
Header Section kid parameter

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/oauth-sd-jwt-vc#99]
Section 5 describes how to use `iss` and well-known directory to fetch the issuer key and verify the VC.
In my opinion it makes sense to name the `kid` parameter as a SHOULD or MAY in section 4.2.1 and make a link to Section 5.

**Comment by peppelinux** [comment]
the kid allows an easy lookup of the key, since it should not collide to any other kid value, it should be created according to rfc7638
it is like a primary key in a sql schema, better having it and by default with a non colliding value

**Comment by tlodderstedt** [comment]
There are different ways to convey key material in an SD-JWT VC. I thus would not add text specific to JWT Issuer Metadata in Section 4.2.1.. 

I would prefer if the metadata section would state something like "if this mechanism is used, the issuer MAY need to add a kid to the signed VCs". Otherwise, it is a back and force.

**Comment by awoie** [comment]
I think we should add an example to Section 5 that shows the header of an SD-JWT VC with a `kid`. There is no need to fix the example in Section 4.2.1 since the `kid` is only RECOMMENDED when using the JWT (VC) Issuer Metadata which is an OPTIONAL feature. 

From Section 5:
>    It is RECOMMENDED that the JWT contains a kid JWT header parameter
   that can be used to lookup the public key in the JWK Set included by
   value or referenced in the JWT Issuer Metadata.

**Comment by awoie** [comment]
As discussed on the SD-JWT VC editor's call today, we will add `kid` to the SD-JWT VC example. To do that, we would need to change the sd-jwt script since we cannot set JWT header params in the script config yet.

@danielfett can you change that? We would need to add:

```
            "kid":"doc-signer-05-25-2022",
```

**Comment by danielfett** [comment]
Fixed by PR #167
